# Generated by Django 5.2.17 on 2026-09-22 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/%Y/%m/', verbose_name='arquivo')),
                ('original_name', models.CharField(max_length=255, verbose_name='nome original')),
                ('size', models.PositiveBigIntegerField(default=0, verbose_name='tamanho (bytes)')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='enviado em')),
            ],
            options={
                'verbose_name': 'arquivo enviado',
                'verbose_name_plural': 'arquivos enviados',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
